name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

#      - name: downcase OWNER
#        run: |
#          echo "OWNER=${GITHUB_REPOSITORY_OWNER,,}" >>${GITHUB_ENV}
#
#      - name: Build docs
#        run: |
#          docker run -it --rm --name my-maven-project -v "$(pwd)":/usr/src/mymaven -w /usr/src/mymaven maven:3.3-jdk-8 mvn compile


      - name: Generate Docs
        run: |
          ls -lhtr
          mvn clean compile

      - name: Add & Commit
        uses: EndBug/add-and-commit@v8.0.1
        with:
          message: ":chart_with_upwards_trend: Update cucumber html"
          push: true


  create-index-page:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get all project names from directory
        id: get-project-names
        run: |
          cd cucumber-html
          projects=""
          for d in */ ; do
            projects="$projects$d;"
          done
          echo $projects
          echo "PROJECTS=$projects" >> $GITHUB_ENV

      - name: Add html tag for every cucumber report
        run: |
          dt=$(TZ=CET date +"%d-%m-%Y %T")
          echo $dt
          sed -i '/<span class="text-muted">/,/<\/span>/c\<span class="text-muted">\nLast updated: '"$dt"'\n<\/span>' index.html
          sed -i '/<div class="list-group mt-3">/,/<\/div>/c\<div class="list-group mt-3">\n<\/div>' index.html
          PROJECTS=${PROJECTS::-1}
          for i in ${PROJECTS//;/ }
          do
              i=${i::-1}
              sed -i '/<div class="list-group mt-3">/a <a href="./cucumber-html/'$i'/cucumber-html-reports/overview-features.html" class="list-group-item list-group-item-action">'$i'</a>' index.html
          done
          git pull

      - name: Add & Commit
        uses: EndBug/add-and-commit@v8.0.1
        with:
          message: ":sparkles: add index.html page"
          push: true